### PR TITLE
Added Str with common string methods.

### PR DESCRIPTION
**Pull request by CarsonF**
Methods:
- replaceFirst (different signature than version in core)
- replaceLast (different signature than version in core)
- removeFirst
- removeLast
- splitFirst
- splitLast
- endsWith
- className
- humanize
- camelCase - rename? Called `camelize` in core
- snakeCase - rename? Called `underscore` in core

### CODE REVIEW

**Comment by GwendolenLynch** [comment]
> camelCase - rename? Called camelize in core
> snakeCase - rename? Called underscore in core

Personally, I prefer this way as the `*Case` confers related semantics :+1:

**Review by GwendolenLynch — APPROVED** [review]
Looks awesome. I pushed a tweak to the test to cover longer strings. While the existing logic is fine, and really can't go far, my trust in long term common sense is another thing. Feel free to squash or drop, it isn't a deal breaker, and I'm just aiming for "helpful"

**Comment by bobdenotter** [comment]
> camelCase - rename? Called camelize in core

"camelize" makes me think of sautéing onions.

> snakeCase - rename? Called underscore in core

"underscore" is a key on your keyboard. `snakeCase` tells you about what it does.. I'd say let's keep these as is. 👍

**Comment by rossriley** [comment]
For reference I used the names that have been standard in Rails since I think they popularised the concept and the language was picked up by other developers.  (http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html)

**Comment by rossriley** [comment]
Incidentally if we are going to use static methods to do these transforms, we already have doctrine inflector included in Bolt via doctrine/common and I think this has most of the transforms we need... https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php

**Comment by CarsonF** [comment]
@rossriley Yes, but I've heard it call snake case more. That's how python refers to it. Happy to discuss more though.

As for doctrine inflector, yes core has that as a dependency but collection, filesystem, session, etc. do not. Also their naming, `classify` and `tableize`, is geared toward ORM context. I think those make even less sense in general use :)

**Pull request merged**
